name: Build Go Project for FreeBSD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@latest

    - name: Set up Go
      uses: actions/setup-go@latest
      with:
        go-version: '1.20'

    - name: Build for FreeBSD
      env:
        GOOS: freebsd
        GOARCH: amd64
      run: |
        go build -o gitea

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: gitea
        path: ./gitea
