name: Build Gitea for FreeBSD with Dependencies

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build with Dependencies
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
        check-latest: true

    - name: Install Node.js (for frontend dependencies)
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Dependencies
      run: |
        make deps-frontend deps-backend

    - name: Build for FreeBSD
      env:
        GOOS: freebsd
        GOARCH: amd64
      run: |
        go build -o gitea

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: gitea-freebsd
        path: ./gitea

